### ISSUE TITLE
Add ability to change the color of the input fields for the bible reference component

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/bible-reference-rcl#18]
Bible Ref field line and dropdown arrows were black and are white in the mockup. 
DoD: line and arrows are white

**Comment by mannycolon** [comment]
What input fields?

**Comment by cckozie** [comment]
This looks good in the current build, but we don't have all the QA labels in bible-reference-rcl so can't tag it.

**Comment by elsylambert** [comment]
Looks good in v0.2.0 build cbad9c9. Line and arrows are white.
