### ISSUE TITLE
Settings popups should close when the user clicks away

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/bible-reference-rcl#24]
When the user opens card settings the settings don't seem to be attached to the three dot icon - they tend to show up in center of screen.  Settings popups should be closed when the user clicks outside of the popup.

DoD: A settings card, invoked from the 3 dot menu, will close when the user clicks outside of the settings card.

-------------------
Also they are modal which means you can't interact with rest of screen.  So we need to do one of 
- dim the rest of the screen to indicate you can't make changes until popup is dismissed
- have the popup close whenever you click off
- or both of the above.

**Comment by birchamp** [comment]
@PhotoNomad0 since the settings popup can change how the content is shown in the cards,  I don't want to dim.  So we will have the popup close when you click off of it. I've changed the issue to reflect that.

**Comment by cckozie** [comment]
Settings popups close when the user clicks away in v0.2.0 build cbad9c9

**Comment by elsylambert** [comment]
Works as expected in v0.9.0 build ab13659.
